### ISSUE TITLE
v0.19 build failed in jitpack.io

### ISSUE THREAD

**Issue by jaslin-W** [qtumproject/qtumj#1]
Hey, teams.
The v0.19-snapshot build failed. There is log
https://jitpack.io/com/github/qtumproject/qtumj/v0.19/build.log

**Comment by ripply** [comment]
Can you try using Gradle 4.8.1, this seems to be an incompatibility with 6.7.1

**Comment by jaslin-W** [comment]
My project uses maven, not gradle. Can this be fixed?

**Comment by ripply** [comment]
Can you try this branch? I tried specifying the Gradle wrapper version that your build process should download
https://github.com/qtumproject/qtumj/tree/specify-gradle-version

**Comment by jaslin-W** [comment]
Thank you very much! It has been fixed.

**Comment by ripply** [comment]
Your welcome, the fix has been merged to master
